
version: '3'

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-broker
        hostname: rabbitmq-broker
        ports:
            - "5672:5672"  # RabbitMQ main port
            - "15672:15672"  # RabbitMQ management plugin port
        environment:
            RABBITMQ_HEARTBEAT: 60
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 5s
            timeout: 10s
            retries: 1

    replay-buffer-service:
        image: replay-buffer-service #ghcr.io/distributedmarlpredatorprey/replay-buffer-service:release-0.3.0
        container_name: replay-buffer-service
        hostname: replay-buffer
        environment:
            PYTHONUNBUFFERED: 1
            GLOBAL_CONFIG_PATH: /usr/app/config/config.yaml
            PREDATOR_DATASET_PATH: /usr/app/dataset/predator_data1.csv
            PREY_DATASET_PATH: /usr/app/dataset/prey_data1.csv
        volumes:
            - ./config/config.yaml:/usr/app/config/config.yaml
            - ./config/replay-buffer/:/usr/app/dataset/
            - ../replay-buffer-service/:/usr/app/

    predator-prey-service-0:
        image: predator-prey-service #ghcr.io/distributedmarlpredatorprey/predator-prey-service:release-0.2.3
        container_name: predator-prey-service-0
        hostname: predator-prey-service-0
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            PYTHONUNBUFFERED: 1
            GLOBAL_CONFIG_PATH: /usr/app/config/config.yaml
            REPLAY_BUFFER_HOST: replay-buffer
            REPLAY_BUFFER_PORT: 80
            BROKER_HOST: rabbitmq-broker
            REL_PATH: 0
            RANDOM_SEED: 0
            MODE: train
        healthcheck:
            test: python3 -m src.main.controllers.agents.policy.predator_prey.actor_receiver_healthcheck
            interval: 2s
            timeout: 5s
            retries: 10
        volumes:
            - ./config/:/usr/app/config/
            - ../predator-prey-service/:/usr/app/
    

    predator-prey-service-1:
        image: predator-prey-service #ghcr.io/distributedmarlpredatorprey/predator-prey-service:release-0.2.3
        container_name: predator-prey-service-1
        hostname: predator-prey-service-1
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            PYTHONUNBUFFERED: 1
            GLOBAL_CONFIG_PATH: /usr/app/config/config.yaml
            REPLAY_BUFFER_HOST: replay-buffer
            REPLAY_BUFFER_PORT: 80
            BROKER_HOST: rabbitmq-broker
            REL_PATH: 1
            RANDOM_SEED: 1
            MODE: train
        healthcheck:
            test: python3 -m src.main.controllers.agents.policy.predator_prey.actor_receiver_healthcheck
            interval: 2s
            timeout: 5s
            retries: 10
        volumes:
            - ./config/:/usr/app/config/
            - ../predator-prey-service/:/usr/app/
    

    predator-prey-service-2:
        image: predator-prey-service #ghcr.io/distributedmarlpredatorprey/predator-prey-service:release-0.2.3
        container_name: predator-prey-service-2
        hostname: predator-prey-service-2
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            PYTHONUNBUFFERED: 1
            GLOBAL_CONFIG_PATH: /usr/app/config/config.yaml
            REPLAY_BUFFER_HOST: replay-buffer
            REPLAY_BUFFER_PORT: 80
            BROKER_HOST: rabbitmq-broker
            REL_PATH: 2
            RANDOM_SEED: 2
            MODE: train
        healthcheck:
            test: python3 -m src.main.controllers.agents.policy.predator_prey.actor_receiver_healthcheck
            interval: 2s
            timeout: 5s
            retries: 10
        volumes:
            - ./config/:/usr/app/config/
            - ../predator-prey-service/:/usr/app/
    

    predator-prey-service-3:
        image: predator-prey-service #ghcr.io/distributedmarlpredatorprey/predator-prey-service:release-0.2.3
        container_name: predator-prey-service-3
        hostname: predator-prey-service-3
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            PYTHONUNBUFFERED: 1
            GLOBAL_CONFIG_PATH: /usr/app/config/config.yaml
            REPLAY_BUFFER_HOST: replay-buffer
            REPLAY_BUFFER_PORT: 80
            BROKER_HOST: rabbitmq-broker
            REL_PATH: 3
            RANDOM_SEED: 3
            MODE: train
        healthcheck:
            test: python3 -m src.main.controllers.agents.policy.predator_prey.actor_receiver_healthcheck
            interval: 2s
            timeout: 5s
            retries: 10
        volumes:
            - ./config/:/usr/app/config/
            - ../predator-prey-service/:/usr/app/
    

    predator-prey-service-4:
        image: predator-prey-service #ghcr.io/distributedmarlpredatorprey/predator-prey-service:release-0.2.3
        container_name: predator-prey-service-4
        hostname: predator-prey-service-4
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            PYTHONUNBUFFERED: 1
            GLOBAL_CONFIG_PATH: /usr/app/config/config.yaml
            REPLAY_BUFFER_HOST: replay-buffer
            REPLAY_BUFFER_PORT: 80
            BROKER_HOST: rabbitmq-broker
            REL_PATH: 4
            RANDOM_SEED: 4
            MODE: train
        healthcheck:
            test: python3 -m src.main.controllers.agents.policy.predator_prey.actor_receiver_healthcheck
            interval: 2s
            timeout: 5s
            retries: 10
        volumes:
            - ./config/:/usr/app/config/
            - ../predator-prey-service/:/usr/app/
    

    learner-service:
        image: learner-service #ghcr.io/distributedmarlpredatorprey/learner-service:main
        container_name: learner-service
        hostname: pred-learner
        depends_on:
            rabbitmq:
                condition: service_healthy
            
            predator-prey-service-0:
                condition: service_healthy
    
            predator-prey-service-1:
                condition: service_healthy
    
            predator-prey-service-2:
                condition: service_healthy
    
            predator-prey-service-3:
                condition: service_healthy
    
            predator-prey-service-4:
                condition: service_healthy
    
        environment:
            PYTHONUNBUFFERED: 1
            GLOBAL_CONFIG_PATH: /usr/app/config/config.yaml
            AGENT_TYPE: predator
            BATCH_SIZE: 64
            REPLAY_BUFFER_HOST: replay-buffer
            REPLAY_BUFFER_PORT: 80
            BROKER_HOST: rabbitmq-broker
        volumes:
            - ./config/config.yaml:/usr/app/config/config.yaml
            - ../learner-service/:/usr/app/
volumes:
    rabbitmq_data:

