environment:
  x_dim: 250
  y_dim: 250
  num_predators: 10
  num_preys: 1
  acc_lower_bound: -1
  acc_upper_bound: 1
  num_states: 30
  num_actions: 2
  r: 10
  vd: 250
  life: 200
  save_experiment_data: true
